### ISSUE TITLE
yaml front matter in font.css

### ISSUE THREAD

**Issue by suburbanbourbon** [invinciblycool/lekh#10]
Is there any reason for adding yaml front matter tags at the start of font.css?
https://github.com/ba11b0y/lekh/blob/722276c0d33d5b76e5425b6b06169e486c5027da/static/css/fonts.css#L1

**Comment by ba11b0y** [comment]
Oops, this was a borrowed code. It should not be there.
Would you be interested in raising a PR for this @suburbanbourbon ?

**Comment by suburbanbourbon** [comment]
done #11 

Also idk why but I am unable to find your theme on https://themes.gohugo.io/ and your earlier theme webpage 404s https://themes.gohugo.io/themes/lekh/

Probably because of this [Themes are removed if not up to date](https://github.com/gohugoio/hugoThemesSiteBuilder#themes-are-removed-if-not-up-to-date). Seems like it is [18 months](https://github.com/gohugoio/hugoThemesSiteBuilder/blob/main/pkg/buildcmd/build.go#L386)

**Comment by ba11b0y** [comment]
Yeah probably! Thanks for the PR, merged it.
I'll try updating this more often
