### ISSUE TITLE
Customisable colours [ enhancement ]

### ISSUE THREAD

**Issue by darshkpatel** [invinciblycool/lekh#2]
A colour selector / config option to change theme

**Comment by darshkpatel** [comment]
The standard sets, eg. Solarized Dark , etc.

**Comment by darshkpatel** [comment]
@invinciblycool There seems to be a selector in demo site, but cant seem to find a reference to it in the code. 
<img width="1552" alt="Screenshot 2020-04-03 at 8 54 00 PM" src="https://user-images.githubusercontent.com/11258286/78377575-662ac780-75ed-11ea-91d3-436c72284746.png">

**Comment by ba11b0y** [comment]
@darshkpatel It's being injected by [dark.js](https://github.com/invinciblycool/lekh/blob/2a7a9b57ffedc0629467e3013a24dc66f723c562/static/js/dark.js#L248)

**Comment by darshkpatel** [comment]
Funny how searching `<div id='mode-selector'>` doesnt yield any results
<img width="1552" alt="Screenshot 2020-04-05 at 4 22 41 PM" src="https://user-images.githubusercontent.com/11258286/78472881-eec67680-7759-11ea-881f-7968f962a417.png">

**Comment by ba11b0y** [comment]
On a side note, I wanted to keep the theme to a bare minimum. Thoughts?

**Comment by darshkpatel** [comment]
Makes sense
