### ISSUE TITLE
Question: How can i show full posts on the homepage

### ISSUE THREAD

**Issue by stephenajulu** [invinciblycool/lekh#5]
Hi, how are you. This theme looks great. But i want to build a micro+link+photo blog with it. So i want to know how i can display full posts on the homepage. Thank you

**Comment by ba11b0y** [comment]
Hello! @stephenajulu 
Thanks for showing interest in the theme.
As the description says, it is a text-focussed theme, hence I had intentionally kept only the permalink to the post on the homepage.
The code below is responsible for rendering the permalink. Shall you wish to display whole posts here you can just put `{{ .Content }}` to render the full content of the post. [Here](https://github.com/invinciblycool/lekh/blob/master/layouts/_default/single.html) is how Hugo renders a single post.
https://github.com/invinciblycool/lekh/blob/56aa828fc157892572576a2ddbec81f14d4fab69/layouts/index.html#L36

I hope this answers your question, if not please feel free to comment.

**Comment by stephenajulu** [comment]
Thank you very much

**Comment by stephenajulu** [comment]
You have been a huge help @invinciblycool  thank you. Started working on turning your theme into a microblog following your advice.

**Comment by ba11b0y** [comment]
Glad to be of help!
