### ISSUE TITLE
Set default mode to dark

### ISSUE THREAD

**Issue by jw4n6** [invinciblycool/lekh#6]
Thank you for an excellent minimal theme. Is it possible to set dark mode as default in config.toml and disable the rest.

**Comment by jw4n6** [comment]
Never mind, noticed this is integrated into the theme with a javascript and probably not an easy task.

**Comment by suburbanbourbon** [comment]
I was able to get a default dark mode by removing the dark.js script and all the references to it. And changed the colors in style.css
```js
body {
    font-family: 'Fira Code';
    line-height: 1.5em;
    font-size: 1.1em;
    color: #c3c3c3;
    max-width: 40rem;
    padding: 2rem;
    margin: auto;
    background: #191919;
    overscroll-behavior-y: none;
}

img {
    max-width: 50%;
}

a {
    color: orange;
}

h1,
h2,
strong {
    color: #d8d8d8;
}
```

But using this method you won't be able to change it on the go. It will remain static
