### ISSUE TITLE
I can't get this theme to work using the steps in Hugo's quickstart

### ISSUE THREAD

**Issue by SaulMagnusson** [invinciblycool/lekh#7]
Hi, I've tried several themes successfully following the steps in https://gohugo.io/getting-started/quick-start/ but with lekh I get the following message when I run `hugo server`.

`Start building sites …
Built in 17 ms
Error: Error building site: failed to render pages: render of "home" failed: "C:\...": execute of template failed: template: index.html:34:11: executing "index.html" at <first .Site.Data.personalize.PostLimit .Pages.ByPublishDate>: error calling first: both limit and seq must be provided`

Any idea what I could try?

**Comment by suyash192** [comment]
Having the same issue. Could have been helpful if there was a config.toml provided in the exampleSite directory.

**Comment by ba11b0y** [comment]
Hey @SaulMagnusson thanks for pointing out the issue.
I've pushed a [fix](https://github.com/invinciblycool/lekh/commit/dc836bde5226f184ee77974fe5db8c4703211de5) and the theme should work now.
Please close the issue if you're able to get it up and running.
Thanks!

**Comment by ba11b0y** [comment]
Hey @suyash192 You can refer to [this personalize.toml](https://github.com/invinciblycool/lekh/blob/master/exampleSite/data/personalize.toml) available in the exampleSite.

**Comment by suyash192** [comment]
Thanks @invinciblycool. Will check it out.

**Comment by SaulMagnusson** [comment]
Its up and running! Thanks for attending to this problem, I'm new to github and hugo and its cool to see this get working. I also like the theme you've created. Cheers.

**Comment by ba11b0y** [comment]
Thanks for your interest @SaulMagnusson and reporting this bug, appreciate it.
Cheers!
