### ISSUE TITLE
What is the purpose of data/personalize.toml file?

### ISSUE THREAD

**Issue by suyash192** [invinciblycool/lekh#8]
All the params in `data/personalize.toml` can be shifted to `config.toml` and the about section can be shifted to an `_index.md` file in the content directory.

Advantages:

1. Single configuration file (config.toml).
2. Seems to be the standard way based on most of the themes I've used (Could be wrong on this one).
3. Possible to embed raw HTML in about section.
4. Syntax highlighting for about section html / markdown.

**Comment by ba11b0y** [comment]
Hey @suyash192 , thanks for the suggestion.
I had kept a different file to keep it decoupled in the beginning.
I think it all makes sense and this change will make the setup easier.
We can go ahead this.
Mind sending a PR?
Or let me know if you aren't interested in contributing, I'll be glad to make the changes.

**Comment by suyash192** [comment]
@invinciblycool Just submitted a PR #9. Please check if everything is alright.
